name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Hello World
    steps:
      - name: say hello
        run: echo "Hello World!"