name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Hello World
    steps:
      - name: Say Hello
        run: echo "Hello World!"
      - name: Now It's
        run: date
      - name: Directory Content
        run: ls -la
