name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20 # the same version used for production
      - name: Install dependencies
        run: npm ci # clean install - suitable for prod env
      - name: Check code style
        run: npx prettier --check .
      - name: Prettier Result
        run: |
          if [ $? -eq 0 ]; then
            echo "Prettier check passed"
          else
            npx prettier --write .
          fi
